version: 2.1
jobs:
  compile:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget
      - run: git clone https://github.com/timangpopi/howcan --depth=1 -b lineage-16.0 .
      - run: wget https://raw.githubusercontent.com/timangpopi/semaphore/master/older
      - run: chmod +x older
      - run: bash older
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
